# Generated by Django 6.1.1 on 2026-09-30 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoPalavraChave',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('palavra', models.CharField(max_length=100)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavras_chave', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Palavra-Chave do Projeto',
                'verbose_name_plural': 'Palavras-Chave do Projeto',
                'ordering': ['palavra'],
            },
        ),
    ]
