# Generated by Django 6.1.1 on 2026-09-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceriaexterna',
            name='tipo_instituicao',
            field=models.CharField(choices=[('GOV_FEDERAL', 'Instituição Governamental Federal'), ('GOV_ESTADUAL', 'Instituição Governamental Estadual'), ('GOV_MUNICIPAL', 'Instituição Governamental Municipal'), ('INICIATIVA_PRIVADA', 'Organização da Iniciativa Privada'), ('MOVIMENTO_SOCIAL', 'Movimento Social'), ('ONG', 'Organização Não Governamental'), ('OUTRO', 'Outros')], max_length=25),
        ),
    ]
