# Generated by Django 6.1.1 on 2026-09-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parceriaexterna',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='parceriaexterna',
            name='descricao_contribuicao',
        ),
        migrations.RemoveField(
            model_name='parceriaexterna',
            name='formalizado_convenio',
        ),
        migrations.RemoveField(
            model_name='parceriaexterna',
            name='nome_contato',
        ),
        migrations.RemoveField(
            model_name='parceriainterna',
            name='descricao_contribuicao',
        ),
        migrations.RemoveField(
            model_name='parceriainterna',
            name='formalizado_convenio',
        ),
        migrations.RemoveField(
            model_name='parceriainterna',
            name='nome_contato',
        ),
        migrations.AddField(
            model_name='parceriaexterna',
            name='participacao',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='parceriaexterna',
            name='sigla_instituicao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parceriainterna',
            name='nome_instituicao',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parceriainterna',
            name='participacao',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='parceriainterna',
            name='sigla_instituicao',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
