# Generated by Django 6.1.1 on 2026-09-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_parceriaexterna_tipo_instituicao'),
        ('projetos', '0002_remove_parceriaexterna_cnpj_and_more'),
    ]

    operations = [
    ]
