# Generated by Django 6.1.1 on 2026-09-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projetopalavrachave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetodescricao',
            name='palavras_chave',
        ),
    ]
