# Generated by Django 6.1.1 on 2026-09-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_remove_projetodescricao_palavras_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='excluido',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
