# Generated by Django 6.1.1 on 2026-09-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculoinstitucional',
            name='tipo_vinculo',
            field=models.CharField(choices=[('PROFESSOR_EFETIVO', 'Professor Efetivo'), ('PROFESSOR_VISITANTE', 'Professor Visitante'), ('PROFESSOR_SUBSTITUTO', 'Professor Substituto/Convidado'), ('TECNICO_ADMINISTRATIVO', 'Técnico-Administrativo'), ('ALUNO_GRADUACAO', 'Aluno de Graduação Não Bolsista'), ('ALUNO_POS_GRADUACAO', 'Aluno de Pós-Graduação'), ('EXTERNO', 'Externo')], max_length=25),
        ),
    ]
