# Generated by Django 6.1.1 on 2026-10-03 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoExtensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inicio', models.DateField(default=datetime.date(2026, 1, 1))),
                ('fim', models.DateField(default=datetime.date(2026, 12, 31))),
                ('aberto', models.BooleanField(default=True, help_text='Chave manual: desligada, o período fica fechado mesmo dentro das datas.')),
                ('mensagem_fechado', models.TextField(blank=True, default='Fora do período de extensão. A criação e a edição de projetos estão indisponíveis no momento.')),
            ],
            options={
                'verbose_name': 'Período de Extensão',
                'verbose_name_plural': 'Período de Extensão',
            },
        ),
    ]
