# Generated by Django 6.1.1 on 2026-09-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vinculoinstitucional_tipo_vinculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaglobal',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
