# Generated by Django 6.1.1 on 2026-09-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pessoaglobal_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaglobal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pessoaglobal',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoaglobal',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoaglobal',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
