# Generated by Django 6.1.1 on 2026-09-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pessoaglobal_is_active_pessoaglobal_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaglobal',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='pessoaglobal',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
