# Generated by Django 6.1.1 on 2026-09-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoaglobal_groups_pessoaglobal_is_active_and_more'),
        ('core', '0005_alter_pessoaglobal_last_login_and_more'),
    ]

    operations = [
    ]
